version: "3.4"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: myshopuser
      POSTGRES_PASSWORD: myshoppassword
      POSTGRES_DB: myshopdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./MyShopBackend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=database;Database=myshopdb;Username=myshopuser;Password=myshoppassword
    depends_on:
      - database
    ports:
      - "5000:80"
    command: bash -c "dotnet ef database update && dotnet run"

  frontend:
    build: ./projekt
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
